#! /bin/sh

sudo chown -R $USER /Users/Shared/Project
sudo chown -R $USER /Users/Shared/Overlays

cd $HOME/Documents/
# -p will mkdir only if it doesn't exist
mkdir -p "Sensel Morph/Bitwig Studio Script Project"
mkdir -p "Sensel Morph/Bitwig Overlay Maps"
cp -r "/Users/Shared/Project/" "Sensel Morph/Bitwig Studio Script Project"
cp -r "/Users/Shared/Overlays/" "Sensel Morph/Bitwig Overlay Maps"

# set permissions for new folder
sudo chown -R $USER "$HOME/Documents/Sensel Morph/Bitwig Studio Script Project"
sudo chown -R $USER "$HOME/Documents/Sensel Morph/Bitwig Overlay Maps"

rm -r /Users/Shared/Project
rm -r /Users/Shared/Overlays
