#! /bin/sh

sudo chown -R $USER /Users/Shared/Sensel_Morph
sudo chown -R $USER /Users/Shared/Project
sudo chown -R $USER /Users/Shared/Overlays

COUNTER=0
find /Applications -maxdepth 1 -name 'Ableton Live 10*' | while read line; do
    if [ "$COUNTER" -eq 0 ]
    then
      cd /
      cp -r /Users/Shared/Sensel_Morph "$line/Contents/App-Resources/MIDI Remote Scripts/"
      sudo chown -R $USER "$line/Contents/App-Resources/MIDI Remote Scripts/"
    fi
    COUNTER=$[$COUNTER +1]
done
cd $HOME/Documents/
mkdir "Sensel Morph"
mkdir "Sensel Morph/Ableton Live Script Project"
cp -r "/Users/Shared/Project/" "Sensel Morph/Ableton Live Script Project"
cp -r "/Users/Shared/Overlays/" "Sensel Morph/Overlay Maps"
sudo chown -R $USER "$HOME/Documents/Sensel Morph/"
sudo chown -R $USER "$HOME/Documents/Sensel Morph/Ableton Live Script Project"
sudo chown -R $USER "$HOME/Documents/Sensel Morph/Overlay Maps"

rm -r /Users/Shared/Sensel_Morph
rm -r /Users/Shared/Project
rm -r /Users/Shared/Overlays
